"""create Message col

Revision ID: 5a37eabfdcae
Revises: e22fbc60246b
Create Date: 2026-04-17 20:01:03.570827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a37eabfdcae'
down_revision: Union[str, Sequence[str], None] = 'e22fbc60246b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('Message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'Message')
    # ### end Alembic commands ###
